BEGIN;

INSERT INTO axxia.cat_icd10 (code,title,parent_code) VALUES
('E11.9','Type 2 diabetes mellitus without complications',''),
('I10','Essential (primary) hypertension',''),
('J06.9','Acute upper respiratory infection, unspecified',''),
('J18.9','Pneumonia, unspecified organism',''),
('N39.0','Urinary tract infection, site not specified',''),
('K21.9','Gastro-esophageal reflux disease without esophagitis',''),
('M54.5','Low back pain',''),
('R51.9','Headache, unspecified',''),
('R07.9','Chest pain, unspecified',''),
('E78.5','Hyperlipidemia, unspecified',''),
('J45.909','Unspecified asthma, uncomplicated',''),
('F41.1','Generalized anxiety disorder',''),
('F32.9','Major depressive disorder, single episode, unspecified',''),
('K52.9','Noninfective gastroenteritis and colitis, unspecified',''),
('A09','Infectious gastroenteritis and colitis, unspecified',''),
('B34.9','Viral infection, unspecified',''),
('L03.90','Cellulitis, unspecified site',''),
('I25.10','Atherosclerotic heart disease of native coronary artery without angina',''),
('I20.9','Angina pectoris, unspecified',''),
('E03.9','Hypothyroidism, unspecified',''),
('E66.9','Obesity, unspecified',''),
('M79.1','Myalgia',''),
('R42','Dizziness and giddiness',''),
('R10.9','Unspecified abdominal pain',''),
('R11.10','Vomiting, unspecified',''),
('R19.7','Diarrhea, unspecified',''),
('H66.90','Otitis media, unspecified, unspecified ear',''),
('J02.9','Acute pharyngitis, unspecified',''),
('J03.90','Acute tonsillitis, unspecified',''),
('J00','Acute nasopharyngitis [common cold]','');


INSERT INTO axxia.cat_snomed_subset (concept_id,fsn,synonyms) VALUES
('271807003','Chest pain','Chest pain|Pain in chest'),
('162397003','Shortness of breath','Dyspnea|Breathlessness'),
('267036007','Cough','Coughing'),
('422587007','Fever','Pyrexia|Raised body temperature'),
('27113001','Headache','Cephalalgia'),
('21522001','Nausea',''),
('422400008','Vomiting','Emesis'),
('62315008','Diarrhea','Loose stools'),
('422034002','Dizziness','Vertigo|Lightheadedness'),
('49727002','Abdominal pain','Stomach ache'),
('49708008','Backache','Back pain'),
('95668009','Sore throat','Throat pain|Pharyngodynia'),
('386661006','Fatigue','Tiredness'),
('29857009','Rash','Skin eruption'),
('422988002','Myalgia','Muscle pain'),
('68142002','Otalgia','Ear pain'),
('267064002','Sneezing',''),
('49711008','Sputum production','Phlegm'),
('699164009','Loss of taste','Ageusia'),
('36955009','Loss of smell','Anosmia'),
('422247000','Palpitations',''),
('161891005','Weight loss',''),
('271327008','Weight gain',''),
('73595000','Anxiety',''),
('35489007','Depressed mood',''),
('162065007','Wheezing',''),
('95315005','Epistaxis','Nosebleed');


INSERT INTO axxia.cat_loinc_subset (loinc,component,property,scale,system,unit_default) VALUES
('718-7','Hemoglobin [Mass/volume] in Blood','MCnc','Qn','Bld','g/dL'),
('4548-4','Hemoglobin A1c/Hemoglobin.total in Blood','MFr','Qn','Bld','%'),
('2339-0','Glucose [Mass/volume] in Blood','MCnc','Qn','Bld','mg/dL'),
('2093-3','Cholesterol [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','mg/dL'),
('2571-8','Triglyceride [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','mg/dL'),
('2085-9','Cholesterol in HDL [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','mg/dL'),
('13457-7','Cholesterol in LDL [Calc] in Serum or Plasma','MCnc','Qn','Ser/Plas','mg/dL'),
('2951-2','Sodium [Moles/volume] in Serum or Plasma','SCnc','Qn','Ser/Plas','mmol/L'),
('2823-3','Potassium [Moles/volume] in Serum or Plasma','SCnc','Qn','Ser/Plas','mmol/L'),
('2075-0','Chloride [Moles/volume] in Serum or Plasma','SCnc','Qn','Ser/Plas','mmol/L'),
('2028-9','Carbon dioxide, total [Moles/volume] in Serum or Plasma','SCnc','Qn','Ser/Plas','mmol/L'),
('2160-0','Creatinine [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','mg/dL'),
('3094-0','Urea nitrogen [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','mg/dL'),
('1975-2','Bilirubin.total [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','mg/dL'),
('6768-6','Alkaline phosphatase [Enzymatic activity/volume] in Serum or Plasma','ACnc','Qn','Ser/Plas','U/L'),
('1742-6','ALT [Enzymatic activity/volume] in Serum or Plasma','ACnc','Qn','Ser/Plas','U/L'),
('1920-8','AST [Enzymatic activity/volume] in Serum or Plasma','ACnc','Qn','Ser/Plas','U/L'),
('2885-2','Protein [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','g/dL'),
('1751-7','Albumin [Mass/volume] in Serum or Plasma','MCnc','Qn','Ser/Plas','g/dL'),
('6690-2','Leukocytes [#/volume] in Blood by Automated count','NCnc','Qn','Bld','10^3/uL'),
('789-8','Erythrocytes [#/volume] in Blood by Automated count','NCnc','Qn','Bld','10^6/uL'),
('777-3','Platelets [#/volume] in Blood by Automated count','NCnc','Qn','Bld','10^3/uL'),
('785-6','Hematocrit [Volume Fraction] of Blood by Automated count','VFr','Qn','Bld','%'),
('11579-0','Thyrotropin (TSH) [Units/volume] in Serum or Plasma','ACnc','Qn','Ser/Plas','uIU/mL');


INSERT INTO axxia.cat_atc_subset (atc,name,level,ddd) VALUES
('A10BA02','Metformin','5','DDD 2 g'),
('C09AA02','Enalapril','5','DDD 10 mg'),
('C10AA05','Atorvastatin','5','DDD 20 mg'),
('C07AB07','Metoprolol','5','DDD 150 mg'),
('B01AC06','Acetylsalicylic acid','5','DDD 3 g (analgesic)'),
('N02BE01','Paracetamol','5','DDD 3 g'),
('R03AC02','Salbutamol','5','DDD 0.8 mg (inh)'),
('A02BC02','Omeprazole','5','DDD 20 mg'),
('J01CA04','Amoxicillin','5','DDD 1.5 g'),
('J01CR02','Amoxicillin/clavulanate','5','DDD 1.5 g (amox)'),
('M01AE01','Ibuprofen','5','DDD 1.2 g'),
('G04CA01','Tamsulosin','5','DDD 0.4 mg'),
('H03AA01','Levothyroxine','5','DDD 0.15 mg'),
('N06AB10','Escitalopram','5','DDD 10 mg'),
('N03AX12','Pregabalin','5','DDD 300 mg'),
('R06AE07','Loratadine','5','DDD 10 mg'),
('M02AA01','Methyl salicylate','4',''),
('A12AX','Electrolyte solutions','3',''),
('A11CC05','Cholecalciferol','5','DDD 10 mcg'),
('B03AA07','Cyanocobalamin','5','DDD 0.01 g');


COMMIT;